TODO: Until we get real data, make synthetic data

#### Temporary: Synthetic Data

In [1]:
# Synthetic Data
import numpy as np
from sklearn.datasets import make_classification
X, y = make_classification(random_state=42)
data = np.concatenate((X, y.reshape(-1, 1)), axis = 1)

### Preprocessing

In [2]:
import preprocess
X_train, X_test, y_train, y_test = preprocess.preprocess(data)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(80, 20) (20, 20) (80,) (20,)


### Modeling

In [6]:
from modeling import model_decisiontree, model_randomforest, model_gradientboosting, model_lightgb
y_pred_dt, dt = model_decisiontree(X_train, X_test, y_train, y_test)
y_pred_rf, rf = model_randomforest(X_train, X_test, y_train, y_test)
y_pred_gb, gb = model_gradientboosting(X_train, X_test, y_train, y_test)
y_pred_lg, lg = model_lightgb(X_train, X_test, y_train, y_test)

[LightGBM] [Info] Number of positive: 43, number of negative: 37
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000252 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 560
[LightGBM] [Info] Number of data points in the train set: 80, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.537500 -> initscore=0.150282
[LightGBM] [Info] Start training from score 0.150282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain

/Users/jonathankahn/anaconda3/envs/SeniorProject/lib/python3.13/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jonathankahn/anaconda3/envs/SeniorProject/lib/python3.13/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


### Evaluation

In [7]:
# basic view for now to see some metrics
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))
print(accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(accuracy_score(y_test, y_pred_gb))
print(confusion_matrix(y_test, y_pred_gb))
print(accuracy_score(y_test, y_pred_lg))
print(confusion_matrix(y_test, y_pred_lg))

0.9
[[11  2]
 [ 0  7]]
0.9
[[11  2]
 [ 0  7]]
0.9
[[11  2]
 [ 0  7]]
0.9
[[11  2]
 [ 0  7]]
